import type { Product, User } from "./types";

export const SEED_USERS: User[] = [
  {
    id: "u-admin",
    username: "admin",
    email: "admin@secondcycle.id",
    password: "admin123",
    role: "admin",
  },
  {
    id: "u-seller-1",
    username: "heritagehouse",
    email: "seller@heritage.id",
    password: "seller123",
    role: "seller",
    storeName: "Heritage House",
    storeAddress: {
      phone: "+62 812 3456 7890",
      city: "Yogyakarta",
      postalCode: "55281",
      addressLine: "Jl. Malioboro No. 12",
    },
  },
  {
    id: "u-seller-2",
    username: "rustandsoul",
    email: "seller@rustsoul.id",
    password: "seller123",
    role: "seller",
    storeName: "Rust & Soul",
    storeAddress: {
      phone: "+62 813 9876 5432",
      city: "Bandung",
      postalCode: "40115",
      addressLine: "Jl. Braga No. 88",
    },
  },
  {
    id: "u-cust-1",
    username: "dianaputri",
    email: "diana@mail.id",
    password: "cust123",
    role: "customer",
    address: {
      phone: "+62 811 2222 3333",
      city: "Jakarta",
      postalCode: "12950",
      addressLine: "Jl. Sudirman Kav. 21",
    },
  },
];

const img = (q: string) =>
  `https://images.unsplash.com/${q}?auto=format&fit=crop&w=1200&q=80`;

export const SEED_PRODUCTS: Product[] = [
  {
    id: "p-1",
    sellerId: "u-seller-1",
    storeName: "Heritage House",
    name: "Brass Reading Lamp, c.1960",
    price: 1250000,
    grade: "A",
    stock: 3,
    imageUrl: img("photo-1513506003901-1e6a229e2d15"),
    description: "Solid brass desk lamp restored to working order. Patina retained.",
    createdAt: Date.now() - 86400000 * 6,
  },
  {
    id: "p-2",
    sellerId: "u-seller-1",
    storeName: "Heritage House",
    name: "Worn Leather Satchel",
    price: 680000,
    grade: "B",
    stock: 1,
    imageUrl: img("photo-1547949003-9792a18a2601"),
    description: "Honest wear, structure intact. Hand-stitched repairs on strap.",
    createdAt: Date.now() - 86400000 * 4,
  },
  {
    id: "p-3",
    sellerId: "u-seller-2",
    storeName: "Rust & Soul",
    name: "Cast Iron Skillet, Pre-loved",
    price: 220000,
    grade: "S",
    stock: 8,
    imageUrl: img("photo-1584990347449-a83d4f593d4b"),
    description: "Re-seasoned. A lifetime of meals ahead.",
    createdAt: Date.now() - 86400000 * 2,
  },
  {
    id: "p-4",
    sellerId: "u-seller-2",
    storeName: "Rust & Soul",
    name: "Wooden Dining Chair (set of 2)",
    price: 1800000,
    grade: "C",
    stock: 2,
    imageUrl: img("photo-1503602642458-232111445657"),
    description: "Mid-century teak. Joints solid, surface scuffed.",
    createdAt: Date.now() - 86400000 * 8,
  },
  {
    id: "p-5",
    sellerId: "u-seller-1",
    storeName: "Heritage House",
    name: "Patinated Copper Vase",
    price: 450000,
    grade: "A",
    stock: 4,
    imageUrl: img("photo-1578500494198-246f612d3b3d"),
    description: "Verdigris finish, original copper beneath.",
    createdAt: Date.now() - 86400000 * 1,
  },
  {
    id: "p-6",
    sellerId: "u-seller-2",
    storeName: "Rust & Soul",
    name: "Vintage Typewriter, Olympia",
    price: 2100000,
    grade: "B",
    stock: 1,
    imageUrl: img("photo-1558461570-6f4b1f9b0c14"),
    description: "Mechanically serviced. Ribbon included.",
    createdAt: Date.now() - 86400000 * 10,
  },
  {
    id: "p-7",
    sellerId: "u-seller-1",
    storeName: "Heritage House",
    name: "Linen Apron, Workshop-worn",
    price: 165000,
    grade: "D",
    stock: 5,
    imageUrl: img("photo-1556905055-8f358a7a47b2"),
    description: "Heavy stains, structurally sound. Character piece.",
    createdAt: Date.now() - 86400000 * 12,
  },
  {
    id: "p-8",
    sellerId: "u-seller-2",
    storeName: "Rust & Soul",
    name: "Enamel Pitcher, Chipped",
    price: 95000,
    grade: "C",
    stock: 6,
    imageUrl: img("photo-1578749556568-bc2c40e68b61"),
    description: "Edge chips, no rust through. Kitchen-ready.",
    createdAt: Date.now() - 86400000 * 3,
  },
];